# HULFT システム動作環境ファイル
# Ver. 7

# ワークファイル作成パス
tmpdir = /tmp

# fifoパス
fifopath = /tmp

# 配信要求受付ポートNo.
# 1 〜 65535
sddport = 

# 集信ポートNo.
# 1 〜 65535
rcvport = 30000

# 要求受付ポートNo.
# 1 〜 65535
obsport = 31000

# 配信プロセスの多重度
# 1 〜 9999
sndpsnum = 2

# 集信プロセスの多重度
# 0 〜 9999  無制限 0
rcvpsnum = 10

# fifo識別番号
# 1 〜 99
sddkeynum = 10

# pidファイル作成パス
piddir = /opt/HULFT/etc

# 漢字コード種
# SJIS or EUC or UTF-8
knjcode = SJIS

# JIS年度
# 78:78年度JIS  83:83年度JIS
jistype = 83

# タブの処理
# 0:スペース変換  1:タブ変換
tabchange = 0

# スペースの扱い
# 0:モード０  1:モード１
spcode = 1

# KEIS全角スペースモード
# 0:モード０(0x4040)  1:モード１(0xA1A1)
keisspmode = 0

# 外字テーブル使用
# 0:使用しない  1:使用する  2:優先的に使用
gaijifile = 0

# 外字未登録時処理
# 0:デフォルトコードに変換  1:エラー
gaijierr = 0

# コード変換モード
# 0:モード０  1:モード１
codechangemode = 0

# パック・ゾーン変換
# 0:モード０ 1:モード１ B:モードＢ F:モードＦ
# 9:モード９ S:モードＳ N:モードＮ
pschg = 0

# ASCII用符号部
# 1:モード１  2:モード２
psascii = 1

# EBCDIC用符号部
# 1:モード１  2:モード２
psebcdic = 1

# Ｘタイプの変換
# 0:モード０  1:モード１
xmode = 0

# 暗号化方式
# 0:HULFT暗号方式 1:暗号出口ルーチン
ciphertype = 0

# 集信オープンモード
# 0:ロック開放まで待たない　1:待つ
rcvfilewait = 1

# 転送グループチェック
# 0:チェックしない　1:あればする　2:する
tgrpchk = 0

# 動的パラメータ指定
# 0:無し 1:有り
dynparam =  0

# メッセージ動的パラメータ指定
# 0:置き換えない　1:配・集信管理情報のみ
# 2:ジョブ起動情報のみ　3:全て
msgdynparam = 0

# 集信多重度オーバーリトライ
# 0:しない　1:する
rcvover_rty = 0

# 配信転送後異常時の処置
# 0:異常終了　1:正常終了
enderrmode = 0

# 再配信待ちキューの削除条件
# 1:ファイルID・ホスト名一致
# 2:ファイルID・ホスト名・ファイル名一致
resenddel = 1

# 集信ファイル最大サイズ
# 1 〜 2の63乗  無制限 0
rcvmaxfilesize = 2147483647

# 自ホスト名
myhostname = HisthDB1

# ソケット接続リトライ回数（回）
# 0 〜 9999
retrycnt = 10

# ソケット接続のリトライ待ち時間 (秒)
# 0 〜 9999
retrytime = 1

# 自動再配信リトライ回数（回）
# 0 〜 9
sockerr_autoretry = 0

# ソケット通信応答待ち時間(秒)
# 10 〜 259200  無限 999999
socktime = 300

# ソケットバッファサイズ
# 0,4096 〜 65520  0:設定しない
socksize = 12288

# 要求受付応答待ち時間(秒)
# 10 〜 259200  無限 999999
obssocktime = 600

# IPバージョン
# 4:IPv4  4/6:IPv4/IPv6  6/4:IPv6/IPv4  6:IPv6
ipversion = 4

# 電文転送タイプ
# N:異常検知優先モード
# S:配信速度優先モード
# R:集信速度優先モード
# A:集配信速度優先モード
proctranstype = A

# 配信デーモン通信方法
# F:FIFO S:ソケット
sddrequestmethod = F

# 管理画面セキュリティチェック
# 1:する 0:しない
admcheck = 0

# 要求受付ホストチェック
# 0:続行する 1:エラーとする
obshstchk = 0

# 操作ログ出力選択
# 0:ログ出力なし
# 1:ファイルアクセスログのみ出力
# 2:コマンド実行ログのみ出力
# 3:全て出力
oplselect = 0

# 操作ログ自動切り替えサイズ
# 0 から 9999 まで(単位：MB)
# 0:切り替えをしない(無制限)
oplchangesize = 0

# 操作ログ切り替え世代管理数
# 2 から 9999まで
oplgenerationcount = 9999

# ユーティリティ応答待ち時間(秒)
# 10 〜 259200  無限 999999
utlwait = 60

# ジョブ終了待ち時間(秒)
# 10 〜 259200  無限 999999
jobwtimeout = 600

# ログ切り替え値（件）
# 0 〜 999999  0:切り替えなし
logdelcount = 0

# 状況表示選択
# 0:配信のみ　1:集・配信
statusdisplay = 1

# HULFT識別文字
hulcharacter = 

# トレース出力バージョン
# 6:トレースログ(V6ヘッダ)、メッセージログを出力
# 7:トレースログ(V7ヘッダ)を出力
tlogver = 7

# トレース出力モード
# 0:トレースログを出力しない
# 1:異常系のトレースログを出力
# 2:すべてのトレースログを出力
tlogmode = 1

# トレース出力ファイル名
tlogfile = /opt/HULFT/etc/trace

# トレース出力ファイルサイズ
# 1 〜 1024(MB)
tlogsize = 10

# XML0バイト集信フラグ
# 0:異常終了　1:正常終了
xmlsw = 0

